### ISSUE TITLE
[CD] Auto-deploy

### ISSUE THREAD

**Issue by gsebil08** [marigold-dev/decookies#39]
### Backend (inside @marigold-dev/deku)

For the "backend" the contract will be originated manually by myself when we will decide do to it.

### Frontend (this repo)

For the frontend, an auto-deploy on a dedicated URL at each commit on `main` branch (this branch is protected, so each commit on it is fully working and tested before) would be perfect.

An URI containing `cookie` and `deku-c` on `marigold.dev` would be awesome (cc @oteku @d4hines)

**Comment by Laucans** [comment]
It's deployed :
- https://cookie.deku-c.gcp.marigold.dev/
- https://cookie.deku-c.marigold.dev/

Auto deploy configured when there is a push on main branch. 

deku-c is on the url, but I can see deku-p on the UI I think we should 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/97902739/201187794-7a0a27ca-263d-486a-93eb-9b13d52c5b3e.png">
