### ISSUE TITLE
Producers can get stuck

### ISSUE THREAD

**Issue by aguillon** [marigold-dev/decookies#46]
Apparently the UI can get stuck if you click too much on cookies producers (e.g. grandmas):
![cursor-grandma-bug](https://user-images.githubusercontent.com/7795522/202143164-46462741-110f-4ad0-91d7-b2393a3c074c.png)

Reloading the page solves this but this is a bit frustrating still.

**Comment by gsebil08** [comment]
Producers are "in delivery" column until the operation is included in a block.

**Comment by gsebil08** [comment]
Ok, I know what happened: nothing.
When buying a building or minting a cookie, I have a simple timeout in the front. The timeout is set to 3seconds.
At the end of the timeout, I refresh the state with the new value fetched from `GET /state/unix`, if your operation had not been included (yet), the counter will stay in this position (1, 0).
Clicking on the cookie will:
- mint a cookie
- refresh the state in 3s
Hence, most of the time, your building will be uptated.

Any idea on how I could manage this possible latency?
