### ISSUE TITLE
Some items get stuck in construction forever

### ISSUE THREAD

**Issue by d4hines** [marigold-dev/decookies#52]
When I click on items rapidly, sometimes they get stuck in production forever. For example, it says I've had 1 grandma in interview for the last 10 minutes. I can no longer make grandmas. I suspect that if a request fails, we never reset the state to allow trying again.

**Comment by aguillon** [comment]
https://github.com/marigold-dev/decookies/issues/46

**Comment by d4hines** [comment]
Ah, my bad. Closing in favor of #46
